name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile DicomAnonymizer.py

      - name: Extract version
        id: get_version
        run: echo "::set-output name=VERSION::$(python setup.py --version)"
        shell: bash

      - name: Upload Executable to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DicomAnonymizer-linux-${{ steps.get_version.outputs.VERSION }}
          path: ./dist/DicomAnonymizer

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile DicomAnonymizer.py

      - name: Extract version
        id: get_version
        run: echo "::set-output name=VERSION::$(python setup.py --version)"
        shell: bash

      - name: Upload Executable to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DicomAnonymizer-windows-${{ steps.get_version.outputs.VERSION }}.exe
          path: ./dist/DicomAnonymizer.exe

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile DicomAnonymizer.py

      - name: Extract version
        id: get_version
        run: echo "::set-output name=VERSION::$(python setup.py --version)"
        shell: bash

      - name: Upload Executable to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DicomAnonymizer-macos-${{ steps.get_version.outputs.VERSION }}
          path: ./dist/DicomAnonymizer

  create-release:
    name: Create Release and Upload Assets
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Windows Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DicomAnonymizer-windows-${{ needs.build-windows.outputs.VERSION }}.exe
          asset_name: DicomAnonymizer-windows-${{ needs.build-windows.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DicomAnonymizer-macos-${{ needs.build-macos.outputs.VERSION }}
          asset_name: DicomAnonymizer-macos-${{ needs.build-macos.outputs.VERSION }}
          asset_content_type: application/octet-stream

      - name: Upload Linux Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DicomAnonymizer-linux-${{ needs.build-linux.outputs.VERSION }}
          asset_name: DicomAnonymizer-linux-${{ needs.build-linux.outputs.VERSION }}
          asset_content_type: application/octet-stream
